// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "before-after" section.

import React from 'react';
import PricingMediaCards from '@/components/sections/pricing/PricingMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function BeforeAfterSection(): React.JSX.Element {
  return (
    <div id="before-after" data-section="before-after">
        <SectionErrorBoundary name="before-after">
              <PricingMediaCards
          tag="Before & After"
          title="Evidence of Excellence"
          description="See the dramatic impact our professional cleaning services have on real spaces."
          plans={[
            {
              tag: "Kitchen",
              price: "Expert Clean",
              period: "Before & After",
              features: [
                "Degreasing",
                "Countertops",
                "Sink sanitation",
              ],
              primaryButton: {
                text: "Book Now",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/horizontal-rearview-maid-classic-uniform-cleaning-apartment-with-vacuum-cleaner-working-living-room-making-space-look-clean-tidy-woman-tries-her-best-meet-employer-demands_176420-14594.jpg",
            },
            {
              tag: "Bathroom",
              price: "Spotless",
              period: "Before & After",
              features: [
                "Tiling scrub",
                "Mirror clarity",
                "Sanitation",
              ],
              primaryButton: {
                text: "Book Now",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/little-boy-with-glasses-cleans-house-with-vacuum-cleaner_169016-11279.jpg",
            },
            {
              tag: "Office Break Room",
              price: "Refreshed",
              period: "Before & After",
              features: [
                "Appliance deep clean",
                "Floor care",
                "Stain removal",
              ],
              primaryButton: {
                text: "Book Now",
                href: "#contact",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/people-taking-care-office-cleaning_23-2149374452.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
