/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Phone, X, Copy, Check } from "lucide-react";
import ScrollReveal from "@/components/ui/ScrollReveal";
import TextAnimation from "@/components/ui/TextAnimation";
import Button from "@/components/ui/Button";

const primaryButton = {
  text: "Get a Free Quote",
  href: "#contact"
};
const secondaryButton = {
  text: "Contact Us Now",
  href: "tel:0200000000"
};

const ContactInline = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText("02 0000 0000");
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <section aria-label="Contact section" className="py-20">
      <div className="w-content-width mx-auto">
        <ScrollReveal variant="fade-blur">
          <div className="flex flex-col items-center gap-8 md:gap-10 py-20 px-8 rounded card">
            <div className="flex flex-col items-center gap-2">
              <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                <p>{"Ready to Start?"}</p>
              </div>

              <TextAnimation
                text={"Get your professional cleaning quote in minutes."}
                variant={"slide-up"}
                gradientText={true}
                tag="h2"
                className="md:max-w-8/10 text-5xl 2xl:text-6xl leading-[1.15] font-semibold text-center text-balance"
              />

              <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
                <Button text={primaryButton.text} href={primaryButton.href} variant="primary" />
                <button
                  type="button"
                  onClick={() => setIsOpen(true)}
                  className="secondary-button cursor-pointer flex items-center gap-2 px-6 py-3 font-medium rounded transition-colors"
                >
                  Contact Us Now
                </button>
              </div>
            </div>
          </div>
        </ScrollReveal>
      </div>

      <AnimatePresence>
        {isOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsOpen(false)}
              className="fixed inset-0 bg-black/60 backdrop-blur-sm"
            ></motion.div>

            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 10 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 10 }}
              transition={{ type: "spring", duration: 0.3 }}
              className="relative z-10 w-full max-w-md p-6 sm:p-8 rounded-xl card shadow-2xl text-foreground"
            >
              <button
                type="button"
                onClick={() => setIsOpen(false)}
                className="absolute top-4 right-4 p-2 text-accent hover:text-foreground transition-colors rounded-full cursor-pointer"
                aria-label="Close modal"
              >
                <X className="w-5 h-5" />
              </button>

              <div className="flex flex-col items-center text-center gap-4">
                <div className="w-14 h-14 rounded-full flex items-center justify-center bg-primary-cta/10 text-primary-cta">
                  <Phone className="w-7 h-7" />
                </div>

                <div>
                  <h3 className="text-2xl font-bold text-foreground">Call JWP Maintenance</h3>
                  <p className="text-accent text-sm mt-1">Our cleaning specialists are ready to answer your call.</p>
                </div>

                <div className="w-full my-2 p-4 rounded-lg card flex items-center justify-between gap-3">
                  <span className="text-xl sm:text-2xl font-mono font-bold tracking-wider text-foreground">
                    02 0000 0000
                  </span>
                  <button
                    type="button"
                    onClick={handleCopy}
                    className="p-2 text-accent hover:text-foreground rounded transition-colors flex items-center gap-1 text-xs cursor-pointer"
                    title="Copy phone number"
                  >
                    {copied ? (
                      <>
                        <Check className="w-4 h-4 text-green-600" />
                        <span className="text-green-600 font-medium">Copied</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-4 h-4" />
                        <span>Copy</span>
                      </>
                    )}
                  </button>
                </div>

                <div className="flex flex-col sm:flex-row gap-3 w-full mt-2">
                  <a
                    href="tel:0200000000"
                    className="primary-button flex-1 py-3 px-4 rounded text-center font-medium flex items-center justify-center gap-2"
                  >
                    <Phone className="w-4 h-4" />
                    Call Now
                  </a>
                  <button
                    type="button"
                    onClick={() => setIsOpen(false)}
                    className="secondary-button flex-1 py-3 px-4 rounded text-center font-medium cursor-pointer"
                  >
                    Close
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </section>
  );
};

export default function ContactSection() {
  return (
    <div data-webild-section="contact" data-section="contact" id="contact">
      <ContactInline />
    </div>
  );
}
