// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="FAQ"
          title="Common Questions"
          description="Find quick answers to your questions about our services."
          items={[
            {
              question: "What areas in Sydney do you cover?",
              answer: "We serve the entire Sydney metropolitan area.",
            },
            {
              question: "Are your supplies eco-friendly?",
              answer: "Yes, we use industry-leading eco-friendly and safe supplies.",
            },
            {
              question: "Can I request regular cleaning?",
              answer: "Absolutely, we offer weekly, bi-weekly, and monthly plans.",
            },
            {
              question: "Are you insured?",
              answer: "Yes, our team is fully insured and background-checked.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/auto-repairman-his-manager-wearing-protective-face-masks-greeting-with-elbows-workshop_637285-7630.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
