// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboard from '@/components/sections/hero/HeroBillboard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboard
          title="Professional Cleaning Services in Sydney"
          description="Reliable. Detailed. Affordable. We provide professional cleaning services for homes, offices, warehouses and commercial properties across Sydney."
          primaryButton={{
            text: "Get a Free Quote",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Call Us",
            href: "tel:0200000000",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/back-view-woman-with-mop_23-2147758723.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
