// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "how-it-works" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HowItWorksSection(): React.JSX.Element {
  return (
    <div id="how-it-works" data-section="how-it-works">
        <SectionErrorBoundary name="how-it-works">
              <MetricsMediaCards
          tag="How It Works"
          title="Simple 3-Step Process"
          description="Getting your space cleaned shouldn't be a challenge. We make it easy."
          metrics={[
            {
              value: "01",
              title: "Request a Quote",
              description: "Tell us about your property and cleaning needs.",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-doing-house-chores-with-vacuum_23-2148394963.jpg",
            },
            {
              value: "02",
              title: "Get Your Quote",
              description: "We provide a clear, competitive price tailored to you.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-woman-cleaning-indoors_23-2150454501.jpg",
            },
            {
              value: "03",
              title: "We Clean",
              description: "Our professional cleaners handle all the hard work.",
              imageSrc: "http://img.b2bpic.net/free-photo/indoor-alone-corridor_1127-279.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
