// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesMediaCarousel from '@/components/sections/features/FeaturesMediaCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesMediaCarousel
          tag="Our Services"
          title="Premium Cleaning for Every Need"
          description="From residential homes to massive commercial warehouses, we handle it all with precision."
          items={[
            {
              title: "Residential Cleaning",
              description: "Regular house cleaning, kitchen & bathroom sanitation, and end-of-lease move-out services.",
              buttonIcon: "Home",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-cleaning-her-home_23-2148118476.jpg",
            },
            {
              title: "Office Cleaning",
              description: "Desk and surface cleaning, waste management, and professional kitchen break room sanitation.",
              buttonIcon: "Briefcase",
              imageSrc: "http://img.b2bpic.net/free-photo/designers-using-3d-printer_23-2151037155.jpg",
            },
            {
              title: "Commercial Cleaning",
              description: "Expert warehouse and industrial cleaning. We cover retail, factories, and shared industrial areas.",
              buttonIcon: "Factory",
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-man-hazmat-suit-cleaning_23-2149345581.jpg",
            },
            {
              title: "End of Lease Cleaning",
              description: "Guaranteed property inspection cleaning, windows, kitchen, and detailed deep floor care.",
              buttonIcon: "ClipboardCheck",
              imageSrc: "http://img.b2bpic.net/free-photo/man-servant-cleaning-house_23-2149530803.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
