// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialRatingCards from '@/components/sections/testimonial/TestimonialRatingCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialRatingCards
          tag="Reviews"
          title="Trusted by Sydney Businesses"
          description="Hear what our clients have to say about our professional service."
          testimonials={[
            {
              name: "Sarah J.",
              role: "Office Manager",
              quote: "The team is consistently thorough and professional.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/middle-aged-hispanic-business-people_23-2151099210.jpg",
            },
            {
              name: "Michael D.",
              role: "Warehouse Owner",
              quote: "Great service for industrial needs. Very reliable.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-mature-businessman-with-cup-coffee-standing-outdoors_23-2147956323.jpg",
            },
            {
              name: "Emily R.",
              role: "Residential Client",
              quote: "My home has never looked this clean. Amazing work.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-woman-cleaning-home_23-2150453326.jpg",
            },
            {
              name: "David K.",
              role: "Retail Manager",
              quote: "Reliable cleaning week after week. Highly recommend.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/happy-auto-repairman-handshaking-with-customer-workshop_637285-8634.jpg",
            },
            {
              name: "Linda M.",
              role: "Property Manager",
              quote: "Their end-of-lease clean is the best in Sydney.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-handsome-middle-aged-business-leader_1262-4822.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
