// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "why-choose-us" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function WhyChooseUsSection(): React.JSX.Element {
  return (
    <div id="why-choose-us" data-section="why-choose-us">
        <SectionErrorBoundary name="why-choose-us">
              <FeaturesRevealCardsBento
          tag="Why Choose Us"
          title="We don't just clean. We manage the cleaning."
          description="Experience reliability and professionalism that allows you to focus on your day."
          items={[
            {
              title: "Reliable Team",
              description: "Background-checked and highly trained professional cleaners.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-young-man-glasses-freelancer-sitting-cafe-with-laptop-drinking-coffee-pointing-fingers_1258-314116.jpg",
            },
            {
              title: "Flexible Schedules",
              description: "Service times tailored to your busy personal or office life.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-young-businesswoman-sitting-workplace-showing-thumb-up-sign_23-2147943730.jpg",
            },
            {
              title: "Competitive Pricing",
              description: "Quality cleaning at market-leading affordable rates.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-man-cleaning-his-house_23-2148112148.jpg",
            },
            {
              title: "Quality Assured",
              description: "Rigorous oversight ensures the standard is always high.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-busy-clean_23-2148480363.jpg",
            },
            {
              title: "Full Equipment",
              description: "We bring our own eco-friendly, industry-grade supplies.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/positive-good-looking-young-asian-woman-with-cheerful-smile-face-spreads-palms-dressed-jacket-meets-friend-stands-indoor_273609-53614.jpg",
            },
            {
              title: "Easy Communication",
              description: "Fast response times for all your booking and scheduling needs.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/busy-day-young-woman-doing-housework-looking-busy_259150-59500.jpg",
            },
            {
              title: "Commercial & Residential",
              description: "Specialized teams for both domestic and corporate properties.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/people-taking-care-office-cleaning_23-2149374451.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
